CPPFLAGS (-D_CONSOLE)
CPPFLAGS (-DBUILD_SEQU)
CPPFLAGS (-DSEQUENCE_CLASS_YARRALINK)
CPPFLAGS (-DSEQUENCE_CLASS)
CPPFLAGS (-DSEQ_NAMESPACE=SEQ_YARRALINK) 

#************************************************************************
# Define the software version 
#************************************************************************
#CPPFLAGS (-DVER_VB)
#CPPFLAGS (-DVER_VB20)
CPPFLAGS (-DVER_VD)
#CPPFLAGS (-DVER_VE)

CPPSOURCES (yarralink)


#************************************************************************
# Comment out following 3 lines for VE 
#************************************************************************
LDLIBS (libRT)   
LDLIBS (SeqBuffer)
LDLIBS (CoilIF)


LDLIBS (Sequence)
LDLIBS (libSBB)
LDLIBS (libSSL)
LDLIBS (libUILink)
LDLIBS (libSeqUtil)
LDLIBS (libSeqUT)
LDLIBS (libUICtrl)
LDLIBS (MrTrace)
LDLIBS (MeasNucleiIF)
LDLIBS (MrProt)
LDLIBS (libUILink)
LDLIBS (libPACE)
LDLIBS (libMES)
LDLIBS (MeasSections)
LDLIBS (MeasPatient)
LDLIBS (libGSL)
LDLIBS (MeasNucleiBase)
LDLIBS (MrBasicObjects)
LDLIBS (libCSL)
LDLIBS (libSL)
LDLIBS (libSeqSysProp)
LDLIBS (MeasNucleiBase)
LDLIBS (MrGenericDC)
LDLIBS (MrParc)
LDLIBS (MrProtocolData)
LDLIBS (UTrace)

LIB (yarralink)
